services:
  - type: web
    name: server
    runtime: docker
    plan: starter
    region: singapore
    branch: staging
    dockerfilePath: ./apps/server/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
